version: '3.9'

services:
  app:
    image: mentisreplay:latest 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    # Uncomment below if you want to use volume mapping
    # volumes:
    #   - ./app_data:/app/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    build:
      context: nginx-reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - mynetwork

volumes:
  certs:
    driver: local
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
