version: '3.9'

services:
  app:
    image: mentisreplay:latest 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./sessions:/sessions

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork



volumes:
  certs:
    driver: local
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge